/**
 * File generated by Magnet rest2mobile 1.1 - Oct 29, 2016 11:00:03 PM
 * @see {@link http://developer.magnet.com}
 */

package pt.olive.katappz.spotifysongpreviewplayer.models.spotify;

import java.util.List;

/**
 * Generated from json example
{
  "album_type" : "album",
  "artists" : [ {
    "external_urls" : {
      "spotify" : "https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU"
    },
    "href" : "https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU",
    "id" : "4gzpq5DPGxSnKTe4SA8HAU",
    "name" : "Coldplay",
    "type" : "artist",
    "uri" : "spotify:artist:4gzpq5DPGxSnKTe4SA8HAU"
  } ],
  "available_markets" : [ "AD", "AR", "AT", "AU", "BE", "BG", "BO", "BR", "CA", "CH", "CL", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "EC", "EE", "ES", "FI", "FR", "GB", "GR", "GT", "HK", "HN", "HU", "ID", "IE", "IS", "IT", "JP", "LI", "LT", "LU", "LV", "MC", "MT", "MX", "MY", "NI", "NL", "NO", "NZ", "PA", "PE", "PH", "PL", "PT", "PY", "SE", "SG", "SK", "SV", "TR", "TW", "US", "UY" ],
  "external_urls" : {
    "spotify" : "https://open.spotify.com/album/0RHX9XECH8IVI3LNgWDpmQ"
  },
  "href" : "https://api.spotify.com/v1/albums/0RHX9XECH8IVI3LNgWDpmQ",
  "id" : "0RHX9XECH8IVI3LNgWDpmQ",
  "images" : [ {
    "height" : 640,
      ...

 */
public class Album {


  private String album_type;


  private List<Artist> artists;


  private List<java.lang.String> available_markets;


  private String href;


  private String id;


  private List<Image> images;


  private String name;


  private String type;


  private String uri;

  public String getId() {
    return id;
  }

  public List<Image> getImages() {
    return images;
  }

  public String getName() {
    return name;
  }

}
