/**
 * File generated by Magnet rest2mobile 1.1 - Oct 29, 2016 11:00:03 PM
 * @see {@link http://developer.magnet.com}
 */

package pt.olive.katappz.spotifysongpreviewplayer.models.spotify;


/**
 * Generated from json example
{
  "external_urls" : {
    "spotify" : "https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU"
  },
  "href" : "https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU",
  "id" : "4gzpq5DPGxSnKTe4SA8HAU",
  "name" : "Coldplay",
  "type" : "artist",
  "uri" : "spotify:artist:4gzpq5DPGxSnKTe4SA8HAU"
}

 */

public class Artist {


  private String href;

  
  private String id;

  
  private String name;

  
  private String type;

  
  private String uri;

  public String getId() {
    return id;
  }
  public String getName() {
    return name;
  }

}
