/**
 * File generated by Magnet rest2mobile 1.1 - Oct 29, 2016 11:00:03 PM
 * @see {@link http://developer.magnet.com}
 */

package pt.olive.katappz.spotifysongpreviewplayer.models.spotify;


/**
 * Generated from json example
{
  "height" : 640,
  "url" : "https://i.scdn.co/image/70d8660d8b802835a280ce75799d30db262f7094",
  "width" : 640
}

 */

public class Image {

  
  private Integer height;

  
  private String url;

  
  private Integer width;

  public Integer getHeight() {
    return height;
  }
  public String getUrl() {
    return url;
  }
  public Integer getWidth() {
    return width;
  }

  /**
  * Builder for Image
  **/
  public static class ImageBuilder {
    private Image toBuild = new Image();

    public ImageBuilder() {
    }

    public Image build() {
      return toBuild;
    }

    public ImageBuilder height(Integer value) {
      toBuild.height = value;
      return this;
    }
    public ImageBuilder url(String value) {
      toBuild.url = value;
      return this;
    }
    public ImageBuilder width(Integer value) {
      toBuild.width = value;
      return this;
    }
  }
}
