/**
 * File generated by Magnet rest2mobile 1.1 - Oct 29, 2016 11:00:03 PM
 * @see {@link http://developer.magnet.com}
 */

package pt.olive.katappz.spotifysongpreviewplayer.models.spotify;


/**
 * Generated from json example
{
  "tracks" : {
    "href" : "https://api.spotify.com/v1/search?query=clocks&offset=0&limit=20&type=track",
    "items" : [ {
      "album" : {
        "album_type" : "album",
        "artists" : [ {
          "external_urls" : {
            "spotify" : "https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU"
          },
          "href" : "https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU",
          "id" : "4gzpq5DPGxSnKTe4SA8HAU",
          "name" : "Coldplay",
          "type" : "artist",
          "uri" : "spotify:artist:4gzpq5DPGxSnKTe4SA8HAU"
        } ],
        "available_markets" : [ "AD", "AR", "AT", "AU", "BE", "BG", "BO", "BR", "CA", "CH", "CL", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "EC", "EE", "ES", "FI", "FR", "GB", "GR", "GT", "HK", "HN", "HU", "ID", "IE", "IS", "IT", "JP", "LI", "LT", "LU", "LV", "MC", "MT", "MX", "MY", "NI", "NL", "NO", "NZ", "PA", "PE", "PH", "PL", "PT", "PY", "SE", "SG", "SK", "SV", "TR", "TW", "US", "UY" ],
        "external_urls" : {
          "spotify" : "https://open.spotify.com/album/0RHX9XECH8IVI3LNgWDpmQ"
        },
          ...

 */

public class SearchResult {

  
  private Tracks tracks;

  public Tracks getTracks() {
    return tracks;
  }

  /**
  * Builder for SearchResult
  **/
  public static class SearchResultBuilder {
    private SearchResult toBuild = new SearchResult();

    public SearchResultBuilder() {
    }

    public SearchResult build() {
      return toBuild;
    }

    public SearchResultBuilder tracks(Tracks value) {
      toBuild.tracks = value;
      return this;
    }
  }
}
